version: "3.9"
services:
  pet-api:
    build: .
    ports:
      - 8001:443
    environment:
      - ASPNETCORE_URLS=https://+
      - ASPNETCORE_HTTPS_PORT=8001
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ${HOME}/.aspnet/https:/https/:ro
